import { JSX } from "react";
import { FaChrome, FaEdge, FaFirefoxBrowser, FaSafari, FaOpera, } from "react-icons/fa";
import { FaBrave } from "react-icons/fa6";
import { SiOperagx, SiTorbrowser } from "react-icons/si";

export const langIcons: Record<string, JSX.Element> = {
  Git: <i className="devicon-git-plain colored"></i>,
  Github: <i className="devicon-github-original"></i>,
  Chrome: <i className="devicon-chrome-plain text-white"></i>,
  Assembly: <i className="devicon-labview-plain colored"></i>,
  "C#": <i className="devicon-csharp-plain colored"></i>,
  "C++": <i className="devicon-cplusplus-plain colored"></i>,
  C: <i className="devicon-c-plain colored"></i>,
  Clojure: <i className="devicon-clojure-plain colored"></i>,
  CoffeeScript: <i className="devicon-coffeescript-plain colored"></i>,
  Crystal: <i className="devicon-crystal-plain colored"></i>,
  CSS: <i className="devicon-css3-plain colored"></i>,
  Dart: <i className="devicon-dart-plain colored"></i>,
  Dockerfile: <i className="devicon-docker-plain"></i>,
  Elixir: <i className="devicon-elixir-plain colored"></i>,
  Elm: <i className="devicon-elm-plain colored"></i>,
  Erlang: <i className="devicon-erlang-plain colored"></i>,
  "F#": <i className="devicon-fsharp-plain colored"></i>,
  Go: <i className="devicon-go-plain colored"></i>,
  Groovy: <i className="devicon-groovy-plain colored"></i>,
  HTML: <i className="devicon-html5-plain colored"></i>,
  Haskell: <i className="devicon-haskell-plain colored"></i>,
  Java: <i className="devicon-java-plain colored" style={{ color: "#ffca2c" }}></i>,
  JavaScript: <i className="devicon-javascript-plain colored"></i>,
  Julia: <i className="devicon-julia-plain colored"></i>,
  "Jupyter Notebook": <i className="devicon-jupyter-plain colored"></i>,
  Kotlin: <i className="devicon-kotlin-plain colored" style={{ color: "#796bdc" }}></i>,
  Latex: <i className="devicon-latex-plain colored"></i>,
  Lua: <i className="devicon-lua-plain-wordmark colored" style={{ color: "#0000d0" }}></i>,
  Matlab: <i className="devicon-matlab-plain colored"></i>,
  Nim: <i className="devicon-nixos-plain colored" style={{ color: "#FFC200" }}></i>,
  Nix: <i className="devicon-nixos-plain colored"></i>,
  ObjectiveC: <i className="devicon-objectivec-plain colored"></i>,
  OCaml: <i className="devicon-ocaml-plain colored"></i>,
  Perl: <i className="devicon-perl-plain colored"></i>,
  PHP: <i className="devicon-php-plain colored"></i>,
  PLSQL: <i className="devicon-sqlite-plain colored"></i>,
  MySQL: <i className="devicon-mysql-original"></i>,
  Processing: <i className="devicon-processing-plain colored" style={{ color: "#0096D8" }}></i>,
  Python: <i className="devicon-python-plain colored" style={{ color: "#3472a6" }}></i>,
  R: <i className="devicon-r-plain colored"></i>,
  React: <i className="devicon-react-original colored"></i>,
  Ruby: <i className="devicon-ruby-plain colored"></i>,
  Rust: <i className="devicon-rust-plain colored" style={{ color: "#DEA584" }}></i>,
  Sass: <i className="devicon-sass-original colored"></i>,
  Scala: <i className="devicon-scala-plain colored"></i>,
  Shell: <i className="devicon-bash-plain"></i>,
  Solidity: <i className="devicon-solidity-plain colored"></i>,
  Stylus: <i className="devicon-stylus-plain colored"></i>,
  Svelte: <i className="devicon-svelte-plain colored"></i>,
  Swift: <i className="devicon-swift-plain colored"></i>,
  Terraform: <i className="devicon-terraform-plain colored"></i>,
  TypeScript: <i className="devicon-typescript-plain colored"></i>,
  "Vim Script": <i className="devicon-vim-plain colored"></i>,
  Vue: <i className="devicon-vuejs-plain colored"></i>,
  Bootstrap: <i className="devicon-bootstrap-plain colored"></i>,
  UML: <i className="devicon-unifiedmodelinglanguage-plain colored"></i>,
};

export const browserIcons: Record<string, JSX.Element> = {
  Chrome: <FaChrome style={{ color: '#4285F4' }} />,
  Edge: <FaEdge style={{ color: '#0078D7' }} />,
  Firefox: <FaFirefoxBrowser style={{ color: '#FF7139' }} />,
  Safari: <FaSafari style={{ color: '#0FB5EE' }} />,
  Opera: <FaOpera style={{ color: '#FF1B2D' }} />,
  Brave: <FaBrave style={{ color: '#FF6600' }} />,
  "Opera GX": <SiOperagx style={{ color: '#FF1B2D' }} />,
  "Tor Browser": <SiTorbrowser style={{ color: '#4A5BB6' }} />,
}